### ISSUE TITLE
Archive project?

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-grunt-plugin#11]
@dongwq @Mogztter Has the Gulp plugin replaced the need for a Grunt plugin? Are we recommending users to migrate? If so, is it time to archive this project?

**Comment by ggrossetie** [comment]
Tough question... I'd say Gulp is more popular than Grunt this day.
Grunt plugin have a fewer downloads than Gulp plugin (but not by a huge margin):
* https://www.npmjs.com/package/grunt-asciidoctor
* https://www.npmjs.com/package/gulp-asciidoctor

The real question is, does someone want to maintain this project ? do we have the resources to do so ? should we focus on only one JavaScript task runner plugin ?

Grunt is now version 1.0.3 and we don't even know if the plugin is still working with the latest version... 

Gulp repository is more active and as mentioned above I think Gulp is more popular so I think we should at least mention that:

- this repository is no longer actively maintained
- we look for a maintainer ?
- we recommend to migrate to Gulp ?

**Comment by mojavelinux** [comment]
Speaking from personal experience, once I discovered Gulp, I had no interest in Grunt. They fill the same need, and Gulp does it a lot better.

I'd say unless someone comes forward to maintain the project, we should archive it to indicate that we're not working on it anymore. We can leave a message in the README that we recommend using Gulp. If later someone wants to revive it, we can always unarchive it.

**Comment by mojavelinux** [comment]
I'm archiving this project. If there are any objections, please raise them in the Asciidoctor chat.
