### ISSUE TITLE
Grunt plugin is overriding the toc position that is set in document

### ISSUE THREAD

**Issue by tsiiskonen** [asciidoctor/asciidoctor-grunt-plugin#6]
I' having the problem that positioning the toc to right side of the document is not working. So line 
``` :toc: right```
is not doing anything. 

I wrote about this issue to asciidoctor.js forum (https://github.com/asciidoctor/asciidoctor.js/issues/116#issuecomment-120249813) and got this answer:

*Aha! I bet you the problem is this line:*

```showToc: true,```

*That is very likely setting the toc attribute in the API and overriding what you have in the document.* *This is likely an issue in the Grunt plugin...Yep*.

https://github.com/asciidoctor/asciidoctor-grunt-plugin/blob/master/tasks/asciidoctor.js#L49

*That's a bug that needs to be reported against the Grunt plugin. It needs to allow the toc to be set to any of the allowed values. Currently, it is hard-coding the value preamble if showToc is set to true and disabling the toc if showToc is set to false.*

Is there anything that you can do to make grunt plugin allow also other toc positions?

**Comment by Mogztter** [comment]
The attached pull request resolves this issue but we can create another issue to allow the toc to be set to any of the allowed values (in the Gruntfile). The allowed values are:

 * left
 * right
 * macro
 * preamble
 * auto (or blank)

**Comment by tsiiskonen** [comment]
Great thanks! This seems to work. Is it possible to release this on to make it possible to have it with npm install? We are building our documentation with multiple machines and it is important that everyone are using same version of tools.

**Comment by anthonny** [comment]
I just published a version 0.2.1 with the fix made by @Mogztter :+1:  Thank you
